### ISSUE TITLE
upload asset gambar disini

### ISSUE THREAD

**Issue by wkwksama** [creativefls/home-fls#1]
untuk gambar logo dan atribut fls. biar seragam nyimpannya disini. nanti di web tinggal manggil link dari gambar disiri

**Comment by wkwksama** [comment]
![logo fls](https://user-images.githubusercontent.com/21119252/34459199-6da1a8b4-ee1b-11e7-8272-c31278d6a74e.png)

**Comment by wkwksama** [comment]
![salinan nuasantara muda](https://user-images.githubusercontent.com/21119252/34459200-78ab465c-ee1b-11e7-9261-87a1dbcca154.png)

**Comment by wkwksama** [comment]
![fls-logo](https://user-images.githubusercontent.com/21119252/34459239-16407fee-ee1d-11e7-94c1-dc6446f962b0.png)

**Comment by hermawanln** [comment]
![logo](https://user-images.githubusercontent.com/27270350/34713842-12f01310-f55a-11e7-985e-fb83403c3f4b.png)

**Comment by hermawanln** [comment]
![photo6244678575332632543](https://user-images.githubusercontent.com/27270350/34720177-5c3e398c-f570-11e7-9aa4-2f340592da2c.jpg)

QR Code FLS Line

**Comment by wkwksama** [comment]
@hermawanln udah dapet yg asli wan?
